### ISSUE TITLE
ERROR Exit code was 1! and create shim fail for AntonOks_scoop-aoks/vs_buildtools-aoks v17.6.3 

### ISSUE THREAD

**Issue by laris** [AntonOks/scoop-aoks#3]
```> scoop install AntonOks_scoop-aoks/vs_buildtools-aoks
Installing 'vs_buildtools-aoks' (17.6.3) [64bit] from AntonOks_scoop-aoks bucket
Loading vs_BuildTools.exe from cache
Checking hash of vs_BuildTools.exe ... ok.
Running installer script...
ERROR Exit code was 1!
Linking ~\scoop\apps\vs_buildtools-aoks\current => ~\scoop\apps\vs_buildtools-aoks\17.6.3
Creating shim for 'LaunchDevCmd'.
Can't shim 'vs\Common7\Tools\LaunchDevCmd.bat': File doesn't exist.
```

I found this package is latest and match hash file.
But it looks like not work and set in good status.

## Bug Report

**Package Name:** [name of package which has bug(s)]

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by AntonOks** [comment]
> 

Thanks for reporting!

Can you pls run it as Admin? Either in an Admin Shell or with "sudo scoop install..." and let me know?

**Comment by laris** [comment]
I did in Admin powershell session.
Finally I fork another repo and install OK.
Sorry I purge my windows and don't test env again.
Let close this case and if any other have such issue please share more detail to reproduce.
